import { StyleSheet } from "react-native";
import { Colors } from "@/constants/colors";

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: Colors.offWhite },

  // Header
  header: { paddingBottom: 20 },
  headerTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingRight: 16,
  },
  backBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 20,
    paddingTop: 12,
    marginBottom: 8,
  },
  auditLogBtn: {
    marginTop: 4,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.25)",
  },
  auditLogBtnText: { fontSize: 12, color: "rgba(255,255,255,0.7)", fontWeight: "600" },
  backArrow: { fontSize: 20, color: "rgba(255,255,255,0.5)" },
  backLabel: { fontSize: 13, color: "rgba(255,255,255,0.5)", fontWeight: "500" },
  headerProjectName: {
    fontSize: 16,
    color: Colors.white,
    fontWeight: "700",
    letterSpacing: 0.3,
    textAlign: "center",
    marginBottom: 8,
  },
  headerRolePillWrap: { alignItems: "center", marginBottom: 12 },
  headerRolePill: {
    backgroundColor: "rgba(201,168,76,0.15)",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 3,
    borderWidth: 1,
    borderColor: "rgba(201,168,76,0.35)",
  },
  headerRolePillText: {
    fontSize: 11,
    fontWeight: "600",
    color: Colors.goldLight,
    letterSpacing: 0.5,
  },
  healthWrap: { alignItems: "center", marginBottom: 12 },
  healthTrend: { fontSize: 13, fontWeight: "600", marginTop: 8 },
  overdueAlert: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    marginTop: 4,
    marginHorizontal: 24,
    backgroundColor: "rgba(231,76,60,0.15)",
    borderRadius: 10,
    paddingVertical: 8,
  },
  overdueAlertText: { fontSize: 13, color: Colors.red, fontWeight: "600" },
  overdueAlertArrow: { fontSize: 16, color: Colors.red },

  // Sub-tab bar
  subTabBar: { flexDirection: "row", backgroundColor: Colors.navy, paddingBottom: 24 },
  subTab: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 10,
    borderTopWidth: 2,
    borderTopColor: "transparent",
  },
  subTabActive: { borderTopColor: Colors.gold },
  subTabText: { fontSize: 13, fontWeight: "600", color: "rgba(255,255,255,0.4)" },
  subTabTextActive: { color: Colors.gold },

  // Body
  body: { flex: 1 },
  bodyContent: { paddingHorizontal: 20, paddingTop: 20, paddingBottom: 32 },

  // Calendar
  calendarWidget: {
    borderRadius: 16,
    overflow: "hidden",
    marginBottom: 16,
  },
  legend: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    justifyContent: "center",
    marginBottom: 24,
  },
  legendItem: { flexDirection: "row", alignItems: "center", gap: 4 },
  legendDot: { width: 8, height: 8, borderRadius: 4 },
  legendLabel: { fontSize: 11, color: Colors.textSecondary },

  // Invoices
  sectionLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: Colors.textSecondary,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 10,
  },
  invoiceCard: {
    backgroundColor: Colors.white,
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
    borderLeftWidth: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 1,
  },
  invoiceRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  invoiceName: { fontSize: 14, fontWeight: "700", color: Colors.textPrimary },
  invoiceNumPill: {
    alignSelf: "flex-start",
    backgroundColor: Colors.greyBg,
    borderRadius: 6,
    paddingHorizontal: 7,
    paddingVertical: 2,
    marginTop: 4,
  },
  invoiceNumText: { fontSize: 10, fontWeight: "700", color: Colors.textSecondary },
  invoiceDate: { fontSize: 12, color: Colors.textSecondary },
  invoiceDays: { fontSize: 12, fontWeight: "600" },
  invoiceAmt: { fontSize: 16, fontWeight: "800", color: Colors.textPrimary },
  statusBadge: { borderRadius: 8, paddingHorizontal: 10, paddingVertical: 3 },
  statusBadgeText: { fontSize: 11, fontWeight: "600" },
  statusDot: { width: 10, height: 10, borderRadius: 5 },

  // My Space stats
  statRow: { flexDirection: "row", gap: 10, marginBottom: 20 },
  statBox: {
    flex: 1,
    backgroundColor: Colors.white,
    borderRadius: 12,
    padding: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 1,
  },
  statBoxLabel: { fontSize: 11, color: Colors.textSecondary, fontWeight: "600", marginBottom: 4 },
  statBoxNum: { fontSize: 22, fontWeight: "800", marginBottom: 2 },
  statBoxSub: { fontSize: 12, color: Colors.textSecondary },

  // Subcontractor
  confirmedText: { fontSize: 12, color: Colors.green, fontWeight: "600" },
  confirmBtn: {
    backgroundColor: Colors.green,
    borderRadius: 8,
    paddingHorizontal: 18,
    paddingVertical: 6,
    alignSelf: "flex-end",
    marginTop: 8,
  },
  confirmBtnText: { fontSize: 12, fontWeight: "700", color: Colors.white },

  // Builder
  actionRow: { flexDirection: "row", gap: 8, marginTop: 8, justifyContent: "flex-end" },
  actionBtn: {
    height: 34,
    borderRadius: 8,
    paddingHorizontal: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  actionBtnText: { fontSize: 12, fontWeight: "700", color: Colors.white },

  sectionDivider: {
    height: 1,
    backgroundColor: "rgba(0,0,0,0.08)",
    marginVertical: 20,
  },

  // Confirm modal
  confirmOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
  },
  confirmBox: {
    backgroundColor: Colors.white,
    borderRadius: 16,
    padding: 24,
    width: "100%",
  },
  confirmTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: Colors.textPrimary,
    marginBottom: 4,
  },
  confirmInvDesc: {
    fontSize: 14,
    color: Colors.textSecondary,
    marginBottom: 2,
  },
  confirmInvAmt: {
    fontSize: 20,
    fontWeight: "800",
    color: Colors.textPrimary,
    marginBottom: 16,
  },
  confirmFieldLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: Colors.textSecondary,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  confirmReasonInput: {
    borderWidth: 1.5,
    borderColor: "rgba(0,0,0,0.12)",
    borderRadius: 10,
    padding: 12,
    fontSize: 14,
    color: Colors.textPrimary,
    marginBottom: 16,
    minHeight: 64,
  },
  confirmHint: {
    fontSize: 13,
    color: Colors.textSecondary,
    marginBottom: 8,
  },
  confirmTypeInput: {
    borderWidth: 1.5,
    borderColor: "rgba(0,0,0,0.12)",
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 15,
    color: Colors.textPrimary,
    marginBottom: 16,
  },
  confirmError: {
    fontSize: 13,
    color: Colors.red,
    marginBottom: 12,
  },
  confirmBtnRow: {
    flexDirection: "row",
    gap: 10,
  },
  confirmCancelBtn: {
    flex: 1,
    height: 44,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: "rgba(0,0,0,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  confirmCancelText: {
    fontSize: 14,
    fontWeight: "600",
    color: Colors.textSecondary,
  },
  confirmActionBtn: {
    flex: 2,
    height: 44,
    borderRadius: 10,
    backgroundColor: Colors.gold,
    alignItems: "center",
    justifyContent: "center",
  },
  confirmActionText: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.white,
  },

  // Placeholder
  placeholder: { flex: 1, alignItems: "center", justifyContent: "center" },
  placeholderText: { fontSize: 18, fontWeight: "700", color: Colors.textPrimary, marginBottom: 8 },
  emptyText: { fontSize: 14, color: Colors.textSecondary, textAlign: "center", marginTop: 16 },
  placeholderSub: { fontSize: 14, color: Colors.textSecondary },

  // Inner sub-tab bar (inside role views)
  innerTabBar: {
    flexDirection: "row",
    backgroundColor: Colors.offWhite,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0,0,0,0.07)",
  },
  innerTab: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: 2,
    borderBottomColor: "transparent",
  },
  innerTabActive: { borderBottomColor: Colors.navy },
  innerTabText: { fontSize: 13, fontWeight: "600", color: Colors.textSecondary },
  innerTabTextActive: { color: Colors.navy },

  // FAB wrap + menu
  fabWrap: { position: "absolute", bottom: 80, right: 20, alignItems: "flex-end" },
  fabMenu: {
    backgroundColor: Colors.white,
    borderRadius: 12,
    marginBottom: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
    overflow: "hidden",
  },
  fabMenuItem: {
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0,0,0,0.06)",
  },
  fabMenuText: { fontSize: 15, fontWeight: "600", color: Colors.navy },
  fabActive: { backgroundColor: Colors.navy },

  // Floating action button
  fab: {
    width: 56,
    height: 56,
    borderRadius: 16,
    backgroundColor: Colors.gold,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 6,
  },
  fabText: { fontSize: 28, color: Colors.white, lineHeight: 32, fontWeight: "300" },

  // Raise Invoice
  raiseBody: { paddingTop: 70, paddingHorizontal: 24, paddingBottom: 48 },
  raiseBack: { alignSelf: "flex-start", marginBottom: 24 },
  raiseBackArrow: { fontSize: 28, color: Colors.gold },
  raiseTitle: { fontSize: 28, fontWeight: "800", color: Colors.white, marginBottom: 6 },
  raiseSubtitle: { fontSize: 14, color: "rgba(255,255,255,0.5)", marginBottom: 36 },
  raiseFieldLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: Colors.goldLight,
    letterSpacing: 0.5,
    textTransform: "uppercase",
    marginBottom: 8,
  },
  raiseInput: {
    height: 52,
    borderWidth: 1.5,
    borderColor: "rgba(201,168,76,0.25)",
    borderRadius: 12,
    paddingHorizontal: 16,
    fontSize: 16,
    marginBottom: 20,
    backgroundColor: "rgba(255,255,255,0.08)",
    color: Colors.white,
  },
  raiseDateWrap: {
    flexDirection: "row",
    alignItems: "center",
    height: 52,
    borderWidth: 1.5,
    borderColor: "rgba(201,168,76,0.25)",
    borderRadius: 12,
    paddingHorizontal: 16,
    backgroundColor: "rgba(255,255,255,0.08)",
    marginBottom: 20,
  },
  raiseCalIcon: { fontSize: 18 },
  raiseMultiline: { height: 100, paddingTop: 14 },
  raisePrimaryBtn: {
    height: 52,
    borderRadius: 12,
    backgroundColor: Colors.gold,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
  },
  raisePrimaryBtnText: { fontSize: 16, fontWeight: "700", color: Colors.navy },

  // Invite footer
  inviteFooter: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: Colors.offWhite,
    borderTopWidth: 1,
    borderTopColor: "rgba(0,0,0,0.06)",
  },
  inviteBtn: {
    borderWidth: 1.5,
    borderColor: Colors.gold,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
  },
  inviteBtnText: { color: Colors.gold, fontSize: 15, fontWeight: "700", letterSpacing: 0.3 },

  // Invite full-screen modal
  inviteScreen: { flex: 1, backgroundColor: Colors.navy },
  inviteHeader: { paddingBottom: 20 },
  inviteBackBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 20,
    paddingTop: 12,
    marginBottom: 8,
  },
  inviteBackArrow: { fontSize: 20, color: "rgba(255,255,255,0.5)" },
  inviteBackLabel: { fontSize: 13, color: "rgba(255,255,255,0.5)", fontWeight: "500" },
  inviteTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: Colors.white,
    paddingHorizontal: 20,
    marginBottom: 4,
  },
  inviteBody: { flex: 1, backgroundColor: Colors.navy },
  inviteBodyContent: { padding: 24, paddingBottom: 48 },
  inviteFieldLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: Colors.gold,
    letterSpacing: 0.5,
    textTransform: "uppercase",
    marginBottom: 8,
  },
  inviteInput: {
    height: 52,
    borderWidth: 1.5,
    borderColor: Colors.gold + "40",
    borderRadius: 12,
    paddingHorizontal: 16,
    fontSize: 16,
    marginBottom: 20,
    backgroundColor: "rgba(255,255,255,0.08)",
    color: Colors.white,
  },
  inviteRoleRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 20 },
  inviteRoleChip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.15)",
    backgroundColor: "rgba(255,255,255,0.05)",
  },
  inviteRoleChipActive: { borderColor: Colors.gold, backgroundColor: Colors.gold + "26" },
  inviteRoleChipText: { fontSize: 14, fontWeight: "500", color: "rgba(255,255,255,0.7)" },
  inviteRoleChipTextActive: { color: Colors.gold, fontWeight: "700" },
  inviteError: { color: Colors.red, fontSize: 13, fontWeight: "600", marginBottom: 8 },
  invitePrimaryBtn: {
    height: 54,
    backgroundColor: Colors.gold,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  invitePrimaryBtnText: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.navy,
    letterSpacing: 0.5,
  },

  // Invite success state
  inviteSuccess: { alignItems: "center", paddingTop: 40 },
  inviteSuccessIcon: {
    width: 72,
    height: 72,
    borderRadius: 18,
    backgroundColor: Colors.green + "26",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
  },
  inviteSuccessTitle: { fontSize: 24, fontWeight: "800", color: Colors.white, marginBottom: 8 },
  inviteSuccessHint: {
    fontSize: 14,
    color: "rgba(255,255,255,0.5)",
    marginBottom: 20,
    textAlign: "center",
  },
  inviteCodeBox: {
    backgroundColor: Colors.gold + "1A",
    borderWidth: 1.5,
    borderColor: Colors.gold + "66",
    borderRadius: 14,
    paddingVertical: 20,
    paddingHorizontal: 40,
    marginBottom: 12,
  },
  inviteCodeText: { fontSize: 36, fontWeight: "800", color: Colors.gold, letterSpacing: 8 },
  copyBtn: {
    borderWidth: 1.5,
    borderColor: Colors.gold + "80",
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 32,
    marginBottom: 16,
  },
  copyBtnText: { fontSize: 14, fontWeight: "600", color: Colors.gold },
  inviteCodeNote: {
    fontSize: 13,
    color: "rgba(255,255,255,0.4)",
    textAlign: "center",
    marginBottom: 32,
  },

  // Invoice Detail Modal
  detailScreen: { flex: 1, backgroundColor: Colors.offWhite },
  detailHeader: { paddingBottom: 20 },
  detailBackBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 20,
    paddingTop: 12,
    marginBottom: 8,
  },
  detailBackArrow: { fontSize: 20, color: "rgba(255,255,255,0.5)" },
  detailBackLabel: { fontSize: 13, color: "rgba(255,255,255,0.5)", fontWeight: "500" },
  detailTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
    marginTop: 4,
    flexWrap: "wrap",
    gap: 8,
  },
  detailTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: Colors.white,
  },
  detailFooter: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    paddingBottom: 28,
    backgroundColor: Colors.white,
    borderTopWidth: 1,
    borderTopColor: Colors.offWhite,
    gap: 8,
  },
  detailFooterRow: {
    flexDirection: "row",
    gap: 10,
  },
  detailBody: { flex: 1 },
  detailBodyContent: { padding: 16, paddingBottom: 48 },
  detailDesc: {
    fontSize: 17,
    fontWeight: "700",
    color: Colors.navy,
    marginBottom: 16,
    lineHeight: 25,
    paddingHorizontal: 4,
  },
  detailSection: {
    backgroundColor: Colors.white,
    borderRadius: 14,
    paddingHorizontal: 20,
    paddingVertical: 4,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  detailSectionLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: Colors.textSecondary,
    letterSpacing: 1,
    marginBottom: 12,
  },
  detailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: Colors.offWhite,
  },
  detailKey: { fontSize: 14, color: Colors.textSecondary, flex: 1, fontWeight: "500" },
  detailVal: { fontSize: 14, color: Colors.textPrimary, flex: 2, textAlign: "right", fontWeight: "600" },
  detailActionBtn: {
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center",
  },
  detailActionBtnText: { fontSize: 15, fontWeight: "700", color: Colors.white },
});
