import { StyleSheet } from "react-native";
import { Colors } from "@/constants/colors";
import { Fonts } from "@/constants/fonts";

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: Colors.white },
  // ── Project shell ─────────────────────────────────────────────────────
  // One green header carrying identity, health and the view switcher, then a
  // white body. Replaces the old split-background hack (two absolutely
  // positioned halves behind a transparent scroll view), which drew a hard
  // colour break across the middle of the screen no matter where you scrolled.
  headerBlock: { backgroundColor: Colors.vouchGreen },
  headerBody: { paddingHorizontal: 16, paddingBottom: 16 },
  headerProjectName: {
    fontSize: 26,
    fontFamily: Fonts.bold,
    color: Colors.white,
    marginBottom: 8,
  },
  headerMetaRow: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 18 },
  headerRolePill: {
    backgroundColor: Colors.whiteGloss,
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  headerRolePillText: { fontSize: 11, fontFamily: Fonts.bold, color: Colors.white },
  headerMeta: {
    flex: 1,
    fontSize: 13,
    fontFamily: Fonts.regular,
    color: Colors.white,
    opacity: 0.75,
  },
  statsRow: { flexDirection: "row", alignItems: "center" },
  stat: { flex: 1, alignItems: "center", gap: 3 },
  statDivider: { width: 1, height: 28, backgroundColor: Colors.whiteInactive },
  statValue: { fontSize: 22, fontFamily: Fonts.extraBold, color: Colors.white },
  statValueAlert: { color: Colors.amber },
  statLabel: {
    fontSize: 9,
    fontFamily: Fonts.bold,
    color: Colors.white,
    opacity: 0.7,
    letterSpacing: 0.8,
  },
  headerTrend: {
    fontSize: 12,
    fontFamily: Fonts.medium,
    color: Colors.white,
    opacity: 0.8,
    textAlign: "center",
    marginTop: 10,
  },
  switcher: {
    flexDirection: "row",
    backgroundColor: Colors.whiteGloss,
    borderRadius: 12,
    padding: 4,
    marginTop: 18,
  },
  switcherTab: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 9,
    borderRadius: 9,
  },
  switcherTabActive: { backgroundColor: Colors.white },
  switcherText: { fontSize: 14, fontFamily: Fonts.semiBold, color: Colors.white },
  switcherTextActive: { color: Colors.vouchGreen },
  body: { flex: 1, backgroundColor: Colors.white },
  bodyContent: { paddingHorizontal: 16, paddingTop: 20, paddingBottom: 32 },

  // Header
  headerTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 8,
    paddingTop: 4,
  },
  backBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 6,
    minHeight: 36,
    minWidth: 44,
    marginBottom: 4,
  },
  auditLogBtn: {
    marginTop: 4,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.25)",
  },
  auditLogBtnText: { fontSize: 12, color: Colors.white, fontFamily: Fonts.semiBold },
  kebabBtn: {
    marginTop: 0,
    paddingHorizontal: 12,
    paddingVertical: 10,
    minWidth: 44,
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  kebabBtnText: { fontSize: 26, color: Colors.white, lineHeight: 28 },
  kebabOverlay: {
    flex: 1,
  },
  kebabMenu: {
    position: "absolute",
    top: 0,
    right: 16,
    backgroundColor: Colors.white,
    borderRadius: 12,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 8,
    minWidth: 160,
  },
  kebabMenuItem: {
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  kebabMenuItemText: {
    fontSize: 14,
    fontFamily: Fonts.semiBold,
    color: Colors.black,
  },
  kebabMenuDivider: {
    height: 1,
    backgroundColor: Colors.grey100,
  },
  backArrow: { fontSize: 18, color: Colors.white },
  backLabel: { fontSize: 13, color: Colors.white, fontFamily: Fonts.semiBold },

  // Compact header (collapsed state)
  compactHeaderInfo: { flex: 1 },
  compactHeaderName: {
    fontSize: 15,
    fontFamily: Fonts.bold,
    color: Colors.white,
    marginBottom: 2,
  },
  compactHeaderTrend: { fontSize: 11, fontFamily: Fonts.semiBold },
  compactHeaderOverdue: {
    fontSize: 11,
    fontFamily: Fonts.semiBold,
    color: Colors.red,
    marginTop: 2,
  },
  overdueAlertArrow: { fontSize: 14, color: Colors.red },

  // Sub-tab bar

  // Body

  // Calendar
  calendarWidget: {
    borderRadius: 16,
    overflow: "hidden",
    marginBottom: 16,
    borderWidth: 1,
    borderColor: Colors.grey300,
    paddingBottom: 6,
  },
  legend: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    justifyContent: "center",
    marginBottom: 24,
  },
  legendItem: { flexDirection: "row", alignItems: "center", gap: 4 },
  legendDot: { width: 8, height: 8, borderRadius: 4 },
  legendLabel: { fontSize: 11, color: Colors.grey500 },

  // Invoices
  sectionLabel: {
    fontSize: 11,
    fontFamily: Fonts.bold,
    color: Colors.grey500,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 10,
  },
  invoiceCard: {
    backgroundColor: Colors.white,
    borderRadius: 16,
    padding: 14,
    marginBottom: 10,
    // The body is white now, so a shadow no longer separates these — the
    // status colour stays as a left rule and a hairline does the rest.
    borderWidth: 1,
    borderColor: Colors.grey300,
    borderLeftWidth: 4,
  },
  invoiceRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  invoiceName: { fontSize: 14, fontFamily: Fonts.bold, color: Colors.black },
  invoiceNumPill: {
    alignSelf: "flex-start",
    backgroundColor: Colors.grey100,
    borderRadius: 6,
    paddingHorizontal: 7,
    paddingVertical: 2,
    marginTop: 4,
  },
  invoiceNumText: { fontSize: 10, fontFamily: Fonts.bold, color: Colors.grey500 },
  invoiceDate: { fontSize: 12, color: Colors.grey500 },
  invoiceDays: { fontSize: 12, fontFamily: Fonts.semiBold },
  invoiceAmt: { fontSize: 16, fontFamily: Fonts.extraBold, color: Colors.black },
  statusBadge: { borderRadius: 8, paddingHorizontal: 10, paddingVertical: 3 },
  statusBadgeText: { fontSize: 11, fontFamily: Fonts.semiBold },
  statusDot: { width: 10, height: 10, borderRadius: 5 },

  // My Space stats
  statRow: { flexDirection: "row", gap: 10, marginBottom: 20 },
  statGrid: { gap: 10, marginBottom: 20 },
  statGridRow: { flexDirection: "row", gap: 10 },
  statBox: {
    flex: 1,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.grey300,
    borderRadius: 16,
    padding: 14,
    gap: 2,
  },
  statBoxLabel: {
    fontSize: 10,
    color: Colors.grey500,
    fontFamily: Fonts.bold,
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  statBoxNum: { fontSize: 24, fontFamily: Fonts.extraBold },
  // Currency needs a smaller size than a bare count to fit a half-width card.
  statBoxNumMoney: { fontSize: 18 },
  statBoxSub: { fontSize: 12, color: Colors.grey500, fontFamily: Fonts.regular },

  // Subcontractor
  confirmedText: { fontSize: 12, color: Colors.green, fontFamily: Fonts.semiBold },
  confirmBtn: {
    backgroundColor: Colors.green,
    borderRadius: 8,
    paddingHorizontal: 18,
    paddingVertical: 6,
    alignSelf: "flex-end",
    marginTop: 8,
  },
  confirmBtnText: { fontSize: 12, fontFamily: Fonts.bold, color: Colors.white },

  // Builder
  actionRow: { flexDirection: "row", gap: 8, marginTop: 8, justifyContent: "flex-end" },
  actionBtn: {
    height: 34,
    borderRadius: 8,
    paddingHorizontal: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  actionBtnText: { fontSize: 12, fontFamily: Fonts.bold, color: Colors.white },

  sectionDivider: {
    height: 1,
    backgroundColor: "rgba(0,0,0,0.08)",
    marginVertical: 20,
  },

  // Confirm modal
  confirmOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
  },
  confirmBox: {
    backgroundColor: Colors.white,
    borderRadius: 16,
    padding: 24,
    width: "100%",
  },
  confirmTitle: {
    fontSize: 18,
    fontFamily: Fonts.extraBold,
    color: Colors.black,
    marginBottom: 4,
  },
  confirmInvDesc: {
    fontSize: 14,
    color: Colors.grey500,
    marginBottom: 2,
  },
  confirmInvAmt: {
    fontSize: 20,
    fontFamily: Fonts.extraBold,
    color: Colors.black,
    marginBottom: 16,
  },
  confirmFieldLabel: {
    fontSize: 12,
    fontFamily: Fonts.semiBold,
    color: Colors.grey500,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  confirmReasonInput: {
    borderWidth: 1.5,
    borderColor: "rgba(0,0,0,0.12)",
    borderRadius: 10,
    padding: 12,
    fontSize: 14,
    color: Colors.black,
    marginBottom: 16,
    minHeight: 64,
  },
  confirmHint: {
    fontSize: 13,
    color: Colors.grey500,
    marginBottom: 8,
  },
  confirmTypeInput: {
    borderWidth: 1.5,
    borderColor: "rgba(0,0,0,0.12)",
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 15,
    color: Colors.black,
    marginBottom: 16,
  },
  confirmError: {
    fontSize: 13,
    color: Colors.red,
    marginBottom: 12,
  },
  confirmBtnRow: {
    flexDirection: "row",
    gap: 10,
  },
  confirmCancelBtn: {
    flex: 1,
    height: 44,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: "rgba(0,0,0,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  confirmCancelText: {
    fontSize: 14,
    fontFamily: Fonts.semiBold,
    color: Colors.grey500,
  },
  confirmActionBtn: {
    flex: 2,
    height: 44,
    borderRadius: 10,
    backgroundColor: Colors.vouchGreen,
    alignItems: "center",
    justifyContent: "center",
  },
  confirmActionText: {
    fontSize: 14,
    fontFamily: Fonts.bold,
    color: Colors.white,
  },

  // Placeholder
  placeholder: { flex: 1, alignItems: "center", justifyContent: "center" },
  placeholderText: { fontSize: 18, fontFamily: Fonts.bold, color: Colors.black, marginBottom: 8 },
  emptyText: {
    fontSize: 14,
    color: Colors.grey500,
    fontFamily: Fonts.regular,
    textAlign: "center",
    backgroundColor: Colors.offWhite,
    borderRadius: 16,
    paddingVertical: 28,
    paddingHorizontal: 16,
    overflow: "hidden",
  },
  placeholderSub: { fontSize: 14, color: Colors.grey500 },

  // Inner sub-tab bar (inside role views)
  // Segmented control rather than a third row of underlined tabs — the screen
  // already has the app tab bar and the project switcher above this.
  innerTabBar: {
    flexDirection: "row",
    backgroundColor: Colors.grey100,
    borderRadius: 12,
    padding: 4,
    marginHorizontal: 16,
    marginTop: 20,
  },
  innerTab: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 9,
    borderRadius: 9,
  },
  innerTabActive: { backgroundColor: Colors.white },
  innerTabText: { fontSize: 14, fontFamily: Fonts.semiBold, color: Colors.grey700 },
  innerTabTextActive: { color: Colors.vouchGreen },

  // FAB wrap + menu
  // `bottom` is set at the call site from the safe-area inset — this screen is
  // pushed over the tab bar, so the old fixed 80 left it floating mid-screen.
  fabWrap: { position: "absolute", right: 20, alignItems: "flex-end" },
  fabBackdrop: { ...StyleSheet.absoluteFillObject },
  fabMenu: {
    backgroundColor: Colors.white,
    borderRadius: 16,
    marginBottom: 12,
    minWidth: 260,
    transformOrigin: "bottom right",
    // A white card floating over a white body needs an edge — the shadow alone
    // left it blending into the page.
    borderWidth: 1,
    borderColor: Colors.grey300,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 6,
    overflow: "hidden",
  },
  fabMenuItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  fabMenuIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: Colors.vouchGreenLight,
    alignItems: "center",
    justifyContent: "center",
  },
  fabMenuDivider: { height: 1, backgroundColor: Colors.grey100, marginHorizontal: 16 },
  fabMenuSub: { fontSize: 12, fontFamily: Fonts.regular, color: Colors.grey500, marginTop: 1 },
  fabMenuText: { fontSize: 15, fontFamily: Fonts.bold, color: Colors.black },
  fabActive: { backgroundColor: Colors.black },

  // Floating action button
  fab: {
    width: 56,
    height: 56,
    borderRadius: 16,
    backgroundColor: Colors.vouchGreen,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 6,
  },
  fabText: { fontSize: 28, color: Colors.white, lineHeight: 32, fontFamily: Fonts.regular },

  // Raise Invoice
  raiseFixedHeader: {
    paddingHorizontal: 24,
    paddingTop: 8,
    paddingBottom: 12,
    backgroundColor: Colors.grey100,
  },
  raiseKeyboardView: { flex: 1 },
  raiseScroll: { flex: 1 },
  raiseBody: { flexGrow: 1, paddingHorizontal: 24, paddingBottom: 72 },
  raiseBack: {
    alignSelf: "flex-start",
    marginBottom: 16,
    minHeight: 44,
    minWidth: 44,
    justifyContent: "center",
    paddingVertical: 8,
    paddingHorizontal: 8,
  },
  raiseBackArrow: { fontSize: 28, color: Colors.black },
  raiseTitle: { fontSize: 28, fontFamily: Fonts.extraBold, color: Colors.black, marginBottom: 6 },
  raiseSubtitle: { fontSize: 14, color: Colors.grey500, marginBottom: 12 },
  raiseFieldLabel: {
    fontSize: 11,
    fontFamily: Fonts.bold,
    color: Colors.grey500,
    letterSpacing: 0.8,
    textTransform: "uppercase",
    marginBottom: 8,
  },
  raiseInput: {
    height: 52,
    borderWidth: 1,
    borderColor: Colors.grey300,
    borderRadius: 12,
    paddingHorizontal: 16,
    fontSize: 16,
    marginBottom: 20,
    backgroundColor: Colors.white,
    color: Colors.black,
  },
  raiseDateWrap: {
    flexDirection: "row",
    alignItems: "center",
    height: 52,
    borderWidth: 1,
    borderColor: Colors.grey300,
    borderRadius: 12,
    paddingHorizontal: 16,
    backgroundColor: Colors.white,
    marginBottom: 20,
  },
  raiseCalIcon: { fontSize: 18 },
  raiseMultiline: { height: 100, paddingTop: 14 },
  partyPickerBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "center",
    paddingHorizontal: 32,
  },
  partyPickerCard: {
    backgroundColor: Colors.white,
    borderRadius: 16,
    paddingVertical: 8,
    maxHeight: 360,
  },
  partyPickerTitle: {
    fontSize: 15,
    fontFamily: Fonts.bold,
    color: Colors.black,
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 8,
  },
  partyPickerList: { paddingHorizontal: 8 },
  partyPickerItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 14,
    borderTopWidth: 1,
    borderTopColor: Colors.grey100,
  },
  partyPickerItemText: { fontSize: 15, fontFamily: Fonts.semiBold, color: Colors.black },
  partyPickerItemRole: { fontSize: 12, fontFamily: Fonts.medium, color: Colors.grey500 },
  raisePrimaryBtn: {
    height: 54,
    borderRadius: 28,
    backgroundColor: Colors.vouchGreen,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
  },
  raisePrimaryBtnText: { fontSize: 16, fontFamily: Fonts.bold, color: Colors.white },

  // Invite footer
  inviteFooter: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: Colors.grey100,
    borderTopWidth: 1,
    borderTopColor: "rgba(0,0,0,0.06)",
  },
  inviteBtn: {
    borderWidth: 1.5,
    borderColor: Colors.vouchGreen,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
  },
  inviteBtnText: {
    color: Colors.vouchGreen,
    fontSize: 15,
    fontFamily: Fonts.bold,
    letterSpacing: 0.3,
  },

  // Invite full-screen modal
  inviteScreen: { flex: 1, backgroundColor: Colors.grey100 },
  inviteHeader: { paddingBottom: 20 },
  inviteBackBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
    minHeight: 44,
    minWidth: 44,
    marginBottom: 8,
  },
  inviteBackArrow: { fontSize: 20, color: Colors.white },
  inviteBackLabel: { fontSize: 13, color: Colors.white, fontFamily: Fonts.medium },
  inviteTitle: {
    fontSize: 22,
    fontFamily: Fonts.extraBold,
    color: Colors.white,
    paddingHorizontal: 20,
    marginBottom: 4,
  },
  inviteBody: { flex: 1, backgroundColor: Colors.grey100 },
  inviteBodyContent: { padding: 24, paddingBottom: 48 },
  inviteFieldLabel: {
    fontSize: 11,
    fontFamily: Fonts.bold,
    color: Colors.grey500,
    letterSpacing: 0.8,
    textTransform: "uppercase",
    marginBottom: 8,
  },
  inviteInput: {
    height: 52,
    borderWidth: 1,
    borderColor: Colors.grey300,
    borderRadius: 12,
    paddingHorizontal: 16,
    fontSize: 16,
    marginBottom: 20,
    backgroundColor: Colors.white,
    color: Colors.black,
  },
  inviteRoleRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 20 },
  inviteRoleChip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: Colors.grey300,
    backgroundColor: Colors.white,
  },
  inviteRoleChipActive: { borderColor: Colors.vouchGreen, backgroundColor: Colors.vouchGreenLight },
  inviteRoleChipText: { fontSize: 14, fontFamily: Fonts.medium, color: Colors.grey500 },
  inviteRoleChipTextActive: { color: Colors.vouchGreen, fontFamily: Fonts.bold },
  inviteError: { color: Colors.red, fontSize: 13, fontFamily: Fonts.semiBold, marginBottom: 8 },
  invitePrimaryBtn: {
    height: 54,
    backgroundColor: Colors.vouchGreen,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
  },
  invitePrimaryBtnText: {
    fontSize: 16,
    fontFamily: Fonts.bold,
    color: Colors.white,
    letterSpacing: 0.5,
  },

  // Invite success state
  inviteSuccess: { alignItems: "center", paddingTop: 40 },
  inviteSuccessIcon: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: Colors.vouchGreen,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
  },
  inviteSuccessTitle: {
    fontSize: 24,
    fontFamily: Fonts.extraBold,
    color: Colors.black,
    marginBottom: 8,
  },
  inviteSuccessHint: {
    fontSize: 14,
    color: Colors.grey500,
    marginBottom: 20,
    textAlign: "center",
  },
  inviteCodeBox: {
    backgroundColor: Colors.vouchGreenLight,
    borderWidth: 1.5,
    borderColor: Colors.vouchGreen + "66",
    borderRadius: 14,
    paddingVertical: 20,
    paddingHorizontal: 40,
    marginBottom: 12,
  },
  inviteCodeText: {
    fontSize: 36,
    fontFamily: Fonts.extraBold,
    color: Colors.vouchGreen,
    letterSpacing: 8,
  },
  copyBtn: {
    borderWidth: 1.5,
    borderColor: Colors.vouchGreen + "80",
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 32,
    marginBottom: 16,
  },
  copyBtnText: { fontSize: 14, fontFamily: Fonts.semiBold, color: Colors.vouchGreen },
  inviteCodeNote: {
    fontSize: 13,
    color: Colors.grey500,
    textAlign: "center",
    marginBottom: 32,
  },

  // Invoice Detail Modal
  detailScreen: { flex: 1, backgroundColor: Colors.grey100 },
  detailHeader: { paddingBottom: 20 },
  detailBackBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
    minHeight: 44,
    minWidth: 44,
    marginBottom: 8,
  },
  detailBackArrow: { fontSize: 20, color: Colors.white },
  detailBackLabel: { fontSize: 13, color: Colors.white, fontFamily: Fonts.medium },
  detailTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
    marginTop: 4,
    flexWrap: "wrap",
    gap: 8,
  },
  detailTitle: {
    fontSize: 18,
    fontFamily: Fonts.bold,
    color: Colors.white,
  },
  detailFooter: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    paddingBottom: 28,
    backgroundColor: Colors.white,
    borderTopWidth: 1,
    borderTopColor: Colors.grey100,
    gap: 8,
  },
  detailFooterRow: {
    flexDirection: "row",
    gap: 10,
  },
  detailBody: { flex: 1 },
  detailBodyContent: { padding: 16, paddingBottom: 48 },
  detailDesc: {
    fontSize: 17,
    fontFamily: Fonts.bold,
    color: Colors.black,
    marginBottom: 16,
    lineHeight: 25,
    paddingHorizontal: 4,
  },
  detailSection: {
    backgroundColor: Colors.white,
    borderRadius: 14,
    paddingHorizontal: 20,
    paddingVertical: 4,
    marginBottom: 16,
    shadowColor: Colors.black,
    shadowOpacity: 0.05,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  detailSectionLabel: {
    fontSize: 11,
    fontFamily: Fonts.bold,
    color: Colors.grey500,
    letterSpacing: 1,
    marginBottom: 12,
  },
  detailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: Colors.grey100,
  },
  detailKey: { fontSize: 14, color: Colors.grey700, flex: 1, fontFamily: Fonts.medium },
  detailVal: {
    fontSize: 14,
    color: Colors.black,
    flex: 2,
    textAlign: "right",
    fontFamily: Fonts.semiBold,
  },
  detailSubVal: {
    fontSize: 12,
    color: Colors.grey700,
    textAlign: "right",
    marginTop: 2,
  },
  detailActionBtn: {
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center",
  },
  detailActionBtnText: { fontSize: 15, fontFamily: Fonts.bold, color: Colors.white },

  // Filter chips
  filterScroll: { flexGrow: 0, marginBottom: 14 },
  filterRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 16 },
  filterChip: {
    borderWidth: 1,
    borderColor: Colors.grey300,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 5,
    backgroundColor: Colors.white,
  },
  filterChipActive: { backgroundColor: Colors.vouchGreen, borderColor: Colors.vouchGreen },
  filterChipText: { fontSize: 13, fontFamily: Fonts.semiBold, color: Colors.grey500 },
  filterChipTextActive: { color: Colors.white },

  // Members modal
  membersContainer: { flex: 1, backgroundColor: Colors.grey100 },
  membersHeader: { paddingBottom: 20 },
  membersTitle: {
    fontSize: 22,
    fontFamily: Fonts.bold,
    color: Colors.white,
    paddingHorizontal: 20,
    paddingBottom: 8,
  },
  membersBody: { paddingHorizontal: 16, paddingTop: 20, paddingBottom: 32 },
  memberRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.white,
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
    gap: 12,
  },
  memberAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Colors.vouchGreen,
    alignItems: "center",
    justifyContent: "center",
  },
  memberAvatarText: { fontSize: 16, fontFamily: Fonts.bold, color: Colors.white },
  memberInfo: { flex: 1 },
  memberName: { fontSize: 14, fontFamily: Fonts.semiBold, color: Colors.black },
  memberEmail: { fontSize: 12, color: Colors.grey500, marginTop: 2 },
  memberRolePill: {
    backgroundColor: Colors.grey100,
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  memberRolePillText: { fontSize: 11, fontFamily: Fonts.semiBold, color: Colors.grey500 },
});
